version: '3.6'
services:
  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    container_name: 'postgres'
    ports:
      - '54310:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.arm64
    container_name: api
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    environment:
      - PORT=${PORT}
      - SERVICE_NAME=${SERVICE_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ELASTIC_NODES=${ELASTIC_NODES}
    depends_on:
      - database
    networks:
      - dev

volumes:
  postgres-data:

networks:
  dev:
    name: dev
