FROM node:lts
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y openssl libc6

WORKDIR /usr/app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000
CMD [ "npm", "run", "start:local"]
